# syntax=docker/dockerfile:1.7

FROM debian:bookworm-slim AS filesystem

RUN install --directory --owner=65532 --group=65532 /out/storage

FROM gcr.io/distroless/base-debian12:nonroot

ARG TARGETPLATFORM

COPY $TARGETPLATFORM/thread-keep-server /usr/local/bin/thread-keep-server
COPY --from=filesystem --chown=65532:65532 /out/storage/ /var/lib/thread-keep/

USER 65532:65532

EXPOSE 8320

ENTRYPOINT ["/usr/local/bin/thread-keep-server"]
