apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thread-keep-runner-artifacts
  namespace: thread-keep-runners
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
